
- name: install ldap related modules
  package: name={{ item }} state=present
  with_items:
    - nss-pam-ldapd

- name: authconfig
  shell: >
    authconfig
    --enablemkhome
    --enableldap
    --enableldapauth
    --ldapserver ldap.sa.csie.ntu.edu.tw
    --ldapbasedn dc=csie,dc=ntu,dc=edu,dc=tw
    --enableldapstarttls
    --update
