- name: install gcc
  package:
    name: gcc
    state: present

- name: install zip
  package:
    name: zip
    state: present

- name: install unzip
  package:
    name: unzip
    state: present

- name: copy source code of challenges
  copy:
    src: ../files/challenges
    dest: /root/
    mode: 0600

- name: copy flags of challenges
  template:
    src: ../templates/flag.mk.j2
    dest: /root/challenges/flag.mk
    mode: 0600

- name: copy flag5
  template:
    src: ../templates/flag5.txt.j2
    dest: /root/challenges/flag5.txt
    mode: 0600
        
- name: compile challenges
  command: make
  args:
    chdir: /root/challenges/
    
- name: make mkhome.sh executable
  file:
    dest: /root/challenges/mkhome.sh
    mode: 700
    
- name: create directory for challenge
  file:
    dest: /usr/share/challenges
    state: directory
    mode: 755
  notify: make home
  
- name: place flag3
  file:
    dest: /usr/share/challenges/{{ flag3 }}
    state: touch
    mode: 444
    
- name: create user user
  user:
    name: NASA
    home: /mnt/nasa/

- name: start_from_scratch script
  copy:
    src: ../files/start_from_scratch
    dest: /usr/bin/start_from_scratch
    mode: 0111
